### ISSUE TITLE
ImportError: cannot import name 'headers' from 'nOBEX' (unknown location)

### ISSUE THREAD

**Issue by virus379-dz** [sgxgsx/mapAccountHijack#1]
I installed it successfully but when i try to execute, I got this error:
Traceback (most recent call last):
  File "/home/user/mapAccountHijack/mapAccountHijack.py", line 3, in <module>
    from mapfunctions import MAPFunctions
  File "/home/user/mapAccountHijack/mapfunctions.py", line 7, in <module>
    from nOBEX import headers
ImportError: cannot import name 'headers' from 'nOBEX' (unknown location)

**Comment by sgxgsx** [comment]
@ahmedlaggoun which python version are you using? 

If you do a clean install as following will this issue go away?

```
git clone https://github.com/sgxgsx/mapAccountHijack
cd mapAccountHijack
git checkout 1c77f19cc755a7aa610ff5ea032a270987b21e38
python3 -m venv .venv
source .venv/bin/activate
chmod +x install.sh
sudo ./install.sh
```

**Comment by virus379-dz** [comment]
> @ahmedlaggoun which python version are you using?
> 
> If you do a clean install as following will this issue go away?
> 
> ```
> git clone https://github.com/sgxgsx/mapAccountHijack
> cd mapAccountHijack
> git checkout 1c77f19cc755a7aa610ff5ea032a270987b21e38
> python3 -m venv .venv
> source .venv/bin/activate
> chmod +x install.sh
> sudo ./install.sh
> ```

I'm using Python 3.9.2
Yes, I installed it exactly as described but the error still persist!

**Comment by virus379-dz** [comment]
Well, I solved it by installing nOBEX manually:
`cd nOBEX`
`pyhon3 setup.py install`
but now i faced another issue:

```python
Traceback (most recent call last):
  File "/home/user/Desktop/mapAccountHijack/mapAccountHijack.py", line 54, in <module>
    send_sms = args.send_sms
AttributeError: 'Namespace' object has no attribute 'send_sms'
```

**Comment by sgxgsx** [comment]
@ahmedlaggoun The last issue you described was fixed in the latest commit. You either had an old python version or you cloned an old repo?
Alternatively, did you execute a command in a virtual environment?

I need to know this, so that other don't have a problem.

**Comment by virus379-dz** [comment]
I cloned the latest version of the repo and All is fine now

**Comment by sgxgsx** [comment]
Hmm, okay. I'll close it then. But if someone else would have the same problem - I'd need your python3 version.
